### ISSUE TITLE
undeclared identifier 'assert'

### ISSUE THREAD

**Issue by amanns92** [Moros1138/pge-template-project#12]
I run cmake . and after this I run make but I get this error:

pge-template-project-main/include/olcPixelGameEngine.h:5977:4: error: use of undeclared identifier 'assert'
                        assert(resultAddMethod);

I install libpng, make, cmake , gcc over home-brew on my Mac.

**Comment by Moros1138** [comment]
This is a problem with the upstream project which can be found here:

https://github.com/OneLoneCoder/olcPixelGameEngine

Please make your report there. Once they provide a fix, I'll update my template project.
